# Webhook listening port
port: 8080
# Number of alerts the webhook queue can contains while waiting for processing
queueCapacity: 500

zabbix:
# Hostname of your zabbix server
    Host: zabbix-server-here
# Trapper port of your zabbix server
    Port: 10051
    HostNodes: [0,1]
